- name: Test vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather Facts
      vmware_cluster_facts:
        username: u
        password: p
        hostname: 10.0.2.15
        validate_certs: no
        datacenter: DC0
        #cluster: DC0_C0
