- name: Harden ESXi Host
  gather_facts: no
  hosts: localhost
  strategy: free
  tasks:
    - name: Get Services
      vmware_host_service_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
      tags: debug
    - name: Get Advanced Options
      vmware_host_config_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
      tags: debug
    - name: Get Firewall Rules
      vmware_host_firewall_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: "cluster01"  
        validate_certs: no
      tags: debug
    - name: Set Advanced Options
      vmware_host_config_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
        options:
            "UserVars.ESXiShellInteractiveTimeOut": 900
            "UserVars.ESXiShellTimeOut": 900
            "UserVars.DcuiTimeOut": 600
            "UserVars.SuppressShellWarning": 0
            "Security.AccountLockFailures": 3
            "Security.AccountUnlockTime": 900
            "Security.PasswordQualityControl": "similar=deny retry=3 min=disabled,disabled,disabled,disabled,15"
            "DCUI.Access": "root"
            "Net.BlockGuestBPDU": 1
            "Config.HostAgent.plugins.solo.enableMob": false
    - name: Set NTP Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
        service_name: ntpd
        state: present
        service_policy: on   
    - name: Set SSH Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
        service_name: TSM-SSH
        state: absent
        service_policy: off  
    - name: Set Shell Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
        service_name: TSM
        state: absent
        service_policy: off    
    - name: Enable Lockdown Mode
      vmware_host_lockdown:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "cluster01"  
        validate_certs: no
        state: present  
    - name: Manage Firewall Rules
      vmware_host_firewall_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        cluster_name: "cluster01"    
        validate_certs: no      
        rules:
          - name: dhcp 
            enabled: False
          - name: DHCPv6
            enabled: False
          - name: iSCSI
            enabled: False
          - name: snmp 
            enabled: False

