- name: Test Create VM 
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            validate_certs: no
            datacenter: lab
            cluster: cluster01
            folder: /lab/vm/
            name: test_vm_0002
            state: poweredon
            guest_id: centos64Guest
            datastore: datastore1
            disk:
            - size_gb: 10
              type: thin
            hardware:
              memory_mb: 256
              num_cpus: 1
              scsi: paravirtual
            networks:
            - name: "DPortGroup2"
              device_type: vmxnet3
      register: deploy_vm