- name: Create VM 
  hosts: localhost
  gather_facts: no
  vars:
    vmcluster: Cluster01
    vmdatacenter: lab
    vmfolder: /lab/vm/
    vmname_list:  
      - { name: 'vm01', datastore: 'datastore1', network: 'DPortGroup1', cpu: '1', mem: '256' }
      - { name: 'vm02', datastore: 'datastore1', network: 'DPortGroup2', cpu: '1', mem: '256' }
  tasks:
    - name: Debug input list (loop)
      debug:
        var: "{{ item }}"
      with_items :  "{{ vmname_list }}"
      tags: debug
    - name: Create a new CentOS VM
      vmware_guest:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            validate_certs: no
            datacenter: "{{ vmdatacenter }}"
            cluster: "{{ vmcluster }}"
            folder: "{{ vmfolder }}"
            name: "{{ item.name }}"
            state: poweredoff
            guest_id: centos64Guest
            datastore: "{{ item.datastore }}"
            disk:
            - size_gb: 10
              type: thin
            hardware:
              memory_mb: "{{ item.mem }}"
              num_cpus: "{{ item.cpu }}"
              scsi: paravirtual
              boot_firmware: efi
            networks:
            - name: "{{ item.network }}"
              device_type: vmxnet3
            customvalues:
            - key: "svga.vgaOnly"
              Value: true
      register: vmdeploy_list
      with_items:  "{{ vmname_list }}"
    - name: Debug result list
      debug:
        var: "{{ vmdeploy_list }}"
      tags: debug
      